var chalk = require('chalk');
module.exports = function banner() {
    console.log(chalk.red("                           .''''"))
    console.log(chalk.red("                           ,''''"))
    console.log(chalk.red("                           ,''''"))
    console.log(chalk.red("                           ,''''"))
    console.log(chalk.red("                        ''''''''''''''''''''''''''':"))
    console.log(chalk.red("                        ''''''''''''''''''''''''''':"))
    console.log(chalk.red("                        ''''''''''''''''''''''''''':"))
    console.log(chalk.red("                        ''''''''''''''''''''''''''':"))
    console.log(chalk.red("                '''';   ''''''''''''''''''''''''''':"))
    console.log(chalk.red("                '''':      ,''''"))
    console.log(chalk.red("                '''':      ,''''"))
    console.log(chalk.red("                '''':      ,''''"))
    console.log(chalk.red("            ''''''''''''.  ,''''''''"))
    console.log(chalk.red("            ''''''''''''.  ,''''''''"))
    console.log(chalk.red("            ''''''''''''.  ,''''''''"))
    console.log(chalk.red("            ''''''''''''.  ,''''''''"))
    console.log(chalk.red("        ''''''''''''''''.  ,''''''''''''                      ;''''"))
    console.log(chalk.red("        ''''''''''''''''.  ,''''''''''''                      ;''''"))
    console.log(chalk.red("        ''''''''''''''''.  ,''''''''''''                      ;''''"))
    console.log(chalk.red("        ''''''''''''''''`  ,''''''''''''                      ;''''"))
    console.log(chalk.red("        ,,,,,,,,,,,,'''''''',,,;''''''''           '''''''''''',,,,"))
    console.log(chalk.red("                    ''''''''   :''''''''           ''''''''''''"))
    console.log(chalk.red("                    ''''''''   :''''''''           ''''''''''''"))
    console.log(chalk.red("    ................''''''''   :''''''''           ''''''''''''"))
    console.log(chalk.red("    ''''''''''''''''''''''''   :''''''''           ''''.```````"))
    console.log(chalk.red("    ''''''''''''''''''''''''   :''''''''           ''''."))
    console.log(chalk.red("    ''''''''''''''''''''''''   :''''''''           ''''."))
    console.log(chalk.red(",:::'''''''''''''''''''''''':::;'''''''':::::::::::''''."))
    console.log(chalk.red("''''               ''''''''''''''''''''''''''''''':"))
    console.log(chalk.red("''''               ''''''''''''''''''''''''''''''':"))
    console.log(chalk.red("''''               ''''''''''''''''''''''''''''''':"))
    console.log(chalk.red("''''       ;;;;;;;;'''''''''''''''''''''''''''''''';;;`"))
    console.log(chalk.red("''''       '''''''''''''''''''''''''''''''''''''''''''."))
    console.log(chalk.red("''''       '''''''''''''''''''''''''''''''''''''''''''."))
    console.log(chalk.red("''''       '''''''''''''''''''''''''''''''''''''''''''."))
    console.log(chalk.red("''''       '''''''''''''''''''''''''''''''''''''''''''."))
    console.log(chalk.red("            '''''       '''''''''''''''''''''''''''''''."))
    console.log(chalk.red("            '''''       '''''''''''''''''''''''''''''''."))
    console.log(chalk.red("            '''''       '''''''''''''''''''''''''''''''."))
    console.log(chalk.red("            '''''''';   '''''''''''''''''''''''''''''''."))
    console.log(chalk.red("                '''':      ,''''       '''''       ''''."))
    console.log(chalk.red("                '''':      ,''''       '''''       ''''."))
    console.log(chalk.red("                '''':      ,''''       '''''       ''''`"))
    console.log(chalk.red("                '''':      ,''''       '''''''''   ''''''''"))
    console.log(chalk.red("                                           '''''      `''''"))
    console.log(chalk.red("                                           '''''      `''''"))
    console.log(chalk.red("                                           '''''      `''''"))
    console.log(chalk.red("                                           ;;;;'''':  `;;;'''''"))
    console.log(chalk.red("                                               '''':      ,''''"))
    console.log(chalk.red("                                               '''':      ,''''"))
    console.log(chalk.red("                                               '''':      ,''''"))
    console.log(chalk.red("                                               ::::.      .::::"))
    console.log('');
    console.log('Tell me a bit about your commit:');
    console.log('');
};
